// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlightData = { latitude: number, longitude: number, heading: number, altitude: number, altitudeAboveGround: number, groundAltitude: number, indicatedAirspeed: number, trueAirspeed: number, groundSpeed: number, verticalSpeed: number | null, pitch: number | null, bank: number | null, fuelTotalQuantity: number | null, fuelTotalQuantityWeight: number | null, flapsHandleIndex: number | null, timestamp: string, };
