{
 "title": "Flight",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"test_bucket\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r._measurement == \"flight\" and (r._field == \"altitude\" or r._field == \"altitude_ground\"))\r\n |> map(fn: (r) => ({r with _value: math.round(x: r._value)}))"
    }
   ]
  },
  {
   "title": "Airspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"test_bucket\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r._measurement == \"flight\" and (r._field == \"airspeed_indicated\" or r._field == \"airspeed_true\"))\r\n |> map(fn: (r) => ({r with _value: math.round(x: r._value)}))"
    }
   ]
  },
  {
   "title": "Vertical Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"test_bucket\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r._measurement == \"flight\" and r._field == \"vertical_speed\")\r\n"
    }
   ]
  }
 ]
}