apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influx:8086
    editable: true
    isDefault: true
    jsonData:
      version: Flux
      organization: test_org
      defaultBucket: test_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_DB_TOKEN}
  - name: InfluxDB2
    type: influxdb
    access: proxy
    url: http://influx:8086
    editable: true
    jsonData:
      version: SQL
      dbName: test_bucket
#      organization: test_org
#      defaultBucket: test_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_DB_TOKEN}
  - name: InfluxDB3
    type: influxdb
    access: proxy
    url: http://influx:8086
    editable: true
#    jsonData:
#      version: SQL
#      dbName: test_bucket
##      organization: test_org
##      defaultBucket: test_bucket
#      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_DB_TOKEN}

