//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "flight_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    pub flight_id: String,
    pub latitude: f64,
    pub longitude: f64,
    pub heading: f64,
    pub altitude: f64,
    pub altitude_above_ground: f64,
    pub ground_altitude: f64,
    pub indicated_airspeed: f64,
    pub true_airspeed: f64,
    pub ground_speed: f64,
    pub vertical_speed: Option<f64>,
    pub pitch: Option<f64>,
    pub bank: Option<f64>,
    pub fuel_total_quantity: Option<f64>,
    pub fuel_total_quantity_weight: Option<f64>,
    pub flaps_handle_index: Option<i32>,
    pub timestamp: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}